version: "3.9"
services:
  chat-app:
    container_name: chat-app
    image: chat-app:1.0.0
    build:
      context: ./chat-app
      target: dev
    volumes:
    - ./chat-app/:/app/
    ports:
      - 3050:3050
  marvel-app:
    container_name: marvel-app
    image: marvel-app:1.0.0
    build:
      context: ./marvel-app
      target: dev
    volumes:
    - ./marvel-app/:/app/
    ports:
      - 3051:3051