version: "3.9"
services:
  chat-app: #docker run -it -p 3050:3050 -v ${PWD}:/app -w /app chat-app:1.0.0 /bin/sh
    container_name: chat-app
    image: chat-app:1.0.0
    build:
      context: ./chat-app
      target: dev
    working_dir: /app
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./chat-app/:/app/
    ports:
      - 3050:3050
  marvel-app:
    container_name: marvel-app
    image: marvel-app:1.0.0
    build:
      context: ./marvel-app
      target: dev
    working_dir: /app
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./marvel-app/:/app/
    ports:
      - 3051:3051