name: Docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: docker build chat-app
      run: 
        docker build ./chat-app -t dabizidabi/chat-app:latest -t dabizidabi/chat-app:${{ GITHUB_SHA }}
    - name: docker build marvel-app
      run: 
        docker build ./marvel-app -t dabizidabi/marvel-app:latest -t dabizidabi/marvel-app:${{ GITHUB_SHA }}
